(use-modules (guest test)
             (guest color))

(define-test (guest color ansi-format)
  (assert-equal? (ansi-format 0) "\x1b[0m")
  (assert-equal? (ansi-format 20) "\x1b[20m")
  (assert-equal? (ansi-format 0 2) "\x1b[0;2m")
  (assert-equal? (ansi-format 0 2 1000) "\x1b[0;2;1000m"))

(define-test (guest color foreground)
  (assert-equal? (foreground #:black "h") "\x1b[30mh\x1b[39m")
  (assert-equal? (foreground #:red "h") "\x1b[31mh\x1b[39m")
  (assert-equal? (foreground #:green "h") "\x1b[32mh\x1b[39m")
  (assert-equal? (foreground #:yellow "h") "\x1b[33mh\x1b[39m")
  (assert-equal? (foreground #:blue "h") "\x1b[34mh\x1b[39m")
  (assert-equal? (foreground #:magenta "h") "\x1b[35mh\x1b[39m")
  (assert-equal? (foreground #:cyan "h") "\x1b[36mh\x1b[39m")
  (assert-equal? (foreground #:white "h") "\x1b[37mh\x1b[39m"))

(define-test (guest color background)
  (assert-equal? (background #:black "h") "\x1b[40mh\x1b[49m")
  (assert-equal? (background #:red "h") "\x1b[41mh\x1b[49m")
  (assert-equal? (background #:green "h") "\x1b[42mh\x1b[49m")
  (assert-equal? (background #:yellow "h") "\x1b[43mh\x1b[49m")
  (assert-equal? (background #:blue "h") "\x1b[44mh\x1b[49m")
  (assert-equal? (background #:magenta "h") "\x1b[45mh\x1b[49m")
  (assert-equal? (background #:cyan "h") "\x1b[46mh\x1b[49m")
  (assert-equal? (background #:white "h") "\x1b[47mh\x1b[49m"))

(define-test (guest color underlined)
  (assert-equal? (underlined "h") "\x1b[4mh\x1b[24m"))

(define-test (guest color blinking)
  (assert-equal? (blinking "h") "\x1b[5mh\x1b[25m"))
