dist: bionic
language: generic


install:
  - sudo apt update
  - sudo apt install -y guile-2.2 lcov
  - gem install coveralls-lcov

script:
  - guile --debug -L $(realpath ..) -s guest test/ --cover "$(printf "guest/%s " *.scm)" --cover-out coverage.info

after_success:
  - lcov -a coverage.info -b $(realpath .) -o coverage.info
  - coveralls-lcov --repo-token $COVERALLS_TOKEN coverage.info
